#!/bin/bash
# Generated Bash script to download ZINC data
set -e  # Exit on error
wget -P zinc_data/BA/AARN http://files.docking.org/3D/BA/AARN/BAAARN.smi
wget -P zinc_data/BA/ABRN http://files.docking.org/3D/BA/ABRN/BAABRN.smi
wget -P zinc_data/BB/AARN http://files.docking.org/3D/BB/AARN/BBAARN.smi
wget -P zinc_data/BB/ABRN http://files.docking.org/3D/BB/ABRN/BBABRN.smi
wget -P zinc_data/BC/AARN http://files.docking.org/3D/BC/AARN/BCAARN.smi
wget -P zinc_data/BC/ABRN http://files.docking.org/3D/BC/ABRN/BCABRN.smi
wget -P zinc_data/BD/AARN http://files.docking.org/3D/BD/AARN/BDAARN.smi
wget -P zinc_data/BD/ABRN http://files.docking.org/3D/BD/ABRN/BDABRN.smi
wget -P zinc_data/BE/AARN http://files.docking.org/3D/BE/AARN/BEAARN.smi
wget -P zinc_data/BE/ABRN http://files.docking.org/3D/BE/ABRN/BEABRN.smi
wget -P zinc_data/BF/AARN http://files.docking.org/3D/BF/AARN/BFAARN.smi
wget -P zinc_data/BF/ABRN http://files.docking.org/3D/BF/ABRN/BFABRN.smi
wget -P zinc_data/CA/AARN http://files.docking.org/3D/CA/AARN/CAAARN.smi
wget -P zinc_data/CA/ABRN http://files.docking.org/3D/CA/ABRN/CAABRN.smi
wget -P zinc_data/CB/AARN http://files.docking.org/3D/CB/AARN/CBAARN.smi
wget -P zinc_data/CB/ABRN http://files.docking.org/3D/CB/ABRN/CBABRN.smi
wget -P zinc_data/CC/AARN http://files.docking.org/3D/CC/AARN/CCAARN.smi
wget -P zinc_data/CC/ABRN http://files.docking.org/3D/CC/ABRN/CCABRN.smi
wget -P zinc_data/CD/AARN http://files.docking.org/3D/CD/AARN/CDAARN.smi
wget -P zinc_data/CD/ABRN http://files.docking.org/3D/CD/ABRN/CDABRN.smi
wget -P zinc_data/CE/AARN http://files.docking.org/3D/CE/AARN/CEAARN.smi
wget -P zinc_data/CE/ABRN http://files.docking.org/3D/CE/ABRN/CEABRN.smi
wget -P zinc_data/CF/AARN http://files.docking.org/3D/CF/AARN/CFAARN.smi
wget -P zinc_data/CF/ABRN http://files.docking.org/3D/CF/ABRN/CFABRN.smi
wget -P zinc_data/DA/AARN http://files.docking.org/3D/DA/AARN/DAAARN.smi
wget -P zinc_data/DA/ABRN http://files.docking.org/3D/DA/ABRN/DAABRN.smi
wget -P zinc_data/DB/AARN http://files.docking.org/3D/DB/AARN/DBAARN.smi
wget -P zinc_data/DB/ABRN http://files.docking.org/3D/DB/ABRN/DBABRN.smi
wget -P zinc_data/DC/AARN http://files.docking.org/3D/DC/AARN/DCAARN.smi
wget -P zinc_data/DC/ABRN http://files.docking.org/3D/DC/ABRN/DCABRN.smi
wget -P zinc_data/DD/AARN http://files.docking.org/3D/DD/AARN/DDAARN.smi
wget -P zinc_data/DD/ABRN http://files.docking.org/3D/DD/ABRN/DDABRN.smi
wget -P zinc_data/DE/AARN http://files.docking.org/3D/DE/AARN/DEAARN.smi
wget -P zinc_data/DE/ABRN http://files.docking.org/3D/DE/ABRN/DEABRN.smi
wget -P zinc_data/DF/AARN http://files.docking.org/3D/DF/AARN/DFAARN.smi
wget -P zinc_data/DF/ABRN http://files.docking.org/3D/DF/ABRN/DFABRN.smi
wget -P zinc_data/EA/AARN http://files.docking.org/3D/EA/AARN/EAAARN.smi
wget -P zinc_data/EA/ABRN http://files.docking.org/3D/EA/ABRN/EAABRN.smi
wget -P zinc_data/EB/AARN http://files.docking.org/3D/EB/AARN/EBAARN.smi
wget -P zinc_data/EB/ABRN http://files.docking.org/3D/EB/ABRN/EBABRN.smi
wget -P zinc_data/EC/AARN http://files.docking.org/3D/EC/AARN/ECAARN.smi
wget -P zinc_data/EC/ABRN http://files.docking.org/3D/EC/ABRN/ECABRN.smi
wget -P zinc_data/ED/AARN http://files.docking.org/3D/ED/AARN/EDAARN.smi
wget -P zinc_data/ED/ABRN http://files.docking.org/3D/ED/ABRN/EDABRN.smi
wget -P zinc_data/EE/AARN http://files.docking.org/3D/EE/AARN/EEAARN.smi
wget -P zinc_data/EE/ABRN http://files.docking.org/3D/EE/ABRN/EEABRN.smi
wget -P zinc_data/EF/AARN http://files.docking.org/3D/EF/AARN/EFAARN.smi
wget -P zinc_data/EF/ABRN http://files.docking.org/3D/EF/ABRN/EFABRN.smi
wget -P zinc_data/FA/AARN http://files.docking.org/3D/FA/AARN/FAAARN.smi
wget -P zinc_data/FA/ABRN http://files.docking.org/3D/FA/ABRN/FAABRN.smi
wget -P zinc_data/FB/AARN http://files.docking.org/3D/FB/AARN/FBAARN.smi
wget -P zinc_data/FB/ABRN http://files.docking.org/3D/FB/ABRN/FBABRN.smi
wget -P zinc_data/FC/AARN http://files.docking.org/3D/FC/AARN/FCAARN.smi
wget -P zinc_data/FC/ABRN http://files.docking.org/3D/FC/ABRN/FCABRN.smi
wget -P zinc_data/FD/AARN http://files.docking.org/3D/FD/AARN/FDAARN.smi
wget -P zinc_data/FD/ABRN http://files.docking.org/3D/FD/ABRN/FDABRN.smi
wget -P zinc_data/FE/AARN http://files.docking.org/3D/FE/AARN/FEAARN.smi
wget -P zinc_data/FE/ABRN http://files.docking.org/3D/FE/ABRN/FEABRN.smi
wget -P zinc_data/FF/AARN http://files.docking.org/3D/FF/AARN/FFAARN.smi
wget -P zinc_data/FF/ABRN http://files.docking.org/3D/FF/ABRN/FFABRN.smi
wget -P zinc_data/GA/AARN http://files.docking.org/3D/GA/AARN/GAAARN.smi
wget -P zinc_data/GA/ABRN http://files.docking.org/3D/GA/ABRN/GAABRN.smi
wget -P zinc_data/GB/AARN http://files.docking.org/3D/GB/AARN/GBAARN.smi
wget -P zinc_data/GB/ABRN http://files.docking.org/3D/GB/ABRN/GBABRN.smi
wget -P zinc_data/GC/AARN http://files.docking.org/3D/GC/AARN/GCAARN.smi
wget -P zinc_data/GC/ABRN http://files.docking.org/3D/GC/ABRN/GCABRN.smi
wget -P zinc_data/GD/AARN http://files.docking.org/3D/GD/AARN/GDAARN.smi
wget -P zinc_data/GD/ABRN http://files.docking.org/3D/GD/ABRN/GDABRN.smi
wget -P zinc_data/GE/AARN http://files.docking.org/3D/GE/AARN/GEAARN.smi
wget -P zinc_data/GE/ABRN http://files.docking.org/3D/GE/ABRN/GEABRN.smi
wget -P zinc_data/HA/AARN http://files.docking.org/3D/HA/AARN/HAAARN.smi
wget -P zinc_data/HA/ABRN http://files.docking.org/3D/HA/ABRN/HAABRN.smi
wget -P zinc_data/HB/AARN http://files.docking.org/3D/HB/AARN/HBAARN.smi
wget -P zinc_data/HB/ABRN http://files.docking.org/3D/HB/ABRN/HBABRN.smi
wget -P zinc_data/HC/AARN http://files.docking.org/3D/HC/AARN/HCAARN.smi
wget -P zinc_data/HC/ABRN http://files.docking.org/3D/HC/ABRN/HCABRN.smi
wget -P zinc_data/HD/AARN http://files.docking.org/3D/HD/AARN/HDAARN.smi
wget -P zinc_data/HD/ABRN http://files.docking.org/3D/HD/ABRN/HDABRN.smi
wget -P zinc_data/HE/AARN http://files.docking.org/3D/HE/AARN/HEAARN.smi
wget -P zinc_data/HE/ABRN http://files.docking.org/3D/HE/ABRN/HEABRN.smi
wget -P zinc_data/IA/AARN http://files.docking.org/3D/IA/AARN/IAAARN.smi
wget -P zinc_data/IA/ABRN http://files.docking.org/3D/IA/ABRN/IAABRN.smi
wget -P zinc_data/IB/AARN http://files.docking.org/3D/IB/AARN/IBAARN.smi
wget -P zinc_data/IB/ABRN http://files.docking.org/3D/IB/ABRN/IBABRN.smi
wget -P zinc_data/IC/AARN http://files.docking.org/3D/IC/AARN/ICAARN.smi
wget -P zinc_data/IC/ABRN http://files.docking.org/3D/IC/ABRN/ICABRN.smi
wget -P zinc_data/ID/AARN http://files.docking.org/3D/ID/AARN/IDAARN.smi
wget -P zinc_data/ID/ABRN http://files.docking.org/3D/ID/ABRN/IDABRN.smi
wget -P zinc_data/IE/AARN http://files.docking.org/3D/IE/AARN/IEAARN.smi
wget -P zinc_data/IE/ABRN http://files.docking.org/3D/IE/ABRN/IEABRN.smi
wget -P zinc_data/JA/AARN http://files.docking.org/3D/JA/AARN/JAAARN.smi
wget -P zinc_data/JA/ABRN http://files.docking.org/3D/JA/ABRN/JAABRN.smi
wget -P zinc_data/JB/AARN http://files.docking.org/3D/JB/AARN/JBAARN.smi
wget -P zinc_data/JB/ABRN http://files.docking.org/3D/JB/ABRN/JBABRN.smi
wget -P zinc_data/JC/AARN http://files.docking.org/3D/JC/AARN/JCAARN.smi
wget -P zinc_data/JC/ABRN http://files.docking.org/3D/JC/ABRN/JCABRN.smi
wget -P zinc_data/JD/AARN http://files.docking.org/3D/JD/AARN/JDAARN.smi
wget -P zinc_data/JD/ABRN http://files.docking.org/3D/JD/ABRN/JDABRN.smi
wget -P zinc_data/JE/AARN http://files.docking.org/3D/JE/AARN/JEAARN.smi
wget -P zinc_data/JE/ABRN http://files.docking.org/3D/JE/ABRN/JEABRN.smi
wget -P zinc_data/BG/AARN http://files.docking.org/3D/BG/AARN/BGAARN.smi
wget -P zinc_data/BG/ABRN http://files.docking.org/3D/BG/ABRN/BGABRN.smi
wget -P zinc_data/BH/AARN http://files.docking.org/3D/BH/AARN/BHAARN.smi
wget -P zinc_data/BH/ABRN http://files.docking.org/3D/BH/ABRN/BHABRN.smi
wget -P zinc_data/BI/AARN http://files.docking.org/3D/BI/AARN/BIAARN.smi
wget -P zinc_data/BI/ABRN http://files.docking.org/3D/BI/ABRN/BIABRN.smi
wget -P zinc_data/BJ/AARN http://files.docking.org/3D/BJ/AARN/BJAARN.smi
wget -P zinc_data/BJ/ABRN http://files.docking.org/3D/BJ/ABRN/BJABRN.smi
wget -P zinc_data/CG/AARN http://files.docking.org/3D/CG/AARN/CGAARN.smi
wget -P zinc_data/CG/ABRN http://files.docking.org/3D/CG/ABRN/CGABRN.smi
wget -P zinc_data/CH/AARN http://files.docking.org/3D/CH/AARN/CHAARN.smi
wget -P zinc_data/CH/ABRN http://files.docking.org/3D/CH/ABRN/CHABRN.smi
wget -P zinc_data/CI/AARN http://files.docking.org/3D/CI/AARN/CIAARN.smi
wget -P zinc_data/CI/ABRN http://files.docking.org/3D/CI/ABRN/CIABRN.smi
wget -P zinc_data/CJ/AARN http://files.docking.org/3D/CJ/AARN/CJAARN.smi
wget -P zinc_data/CJ/ABRN http://files.docking.org/3D/CJ/ABRN/CJABRN.smi
wget -P zinc_data/DG/AARN http://files.docking.org/3D/DG/AARN/DGAARN.smi
wget -P zinc_data/DG/ABRN http://files.docking.org/3D/DG/ABRN/DGABRN.smi
wget -P zinc_data/DH/AARN http://files.docking.org/3D/DH/AARN/DHAARN.smi
wget -P zinc_data/DH/ABRN http://files.docking.org/3D/DH/ABRN/DHABRN.smi
wget -P zinc_data/DI/AARN http://files.docking.org/3D/DI/AARN/DIAARN.smi
wget -P zinc_data/DI/ABRN http://files.docking.org/3D/DI/ABRN/DIABRN.smi
wget -P zinc_data/DJ/AARN http://files.docking.org/3D/DJ/AARN/DJAARN.smi
wget -P zinc_data/DJ/ABRN http://files.docking.org/3D/DJ/ABRN/DJABRN.smi
wget -P zinc_data/EG/AARN http://files.docking.org/3D/EG/AARN/EGAARN.smi
wget -P zinc_data/EG/ABRN http://files.docking.org/3D/EG/ABRN/EGABRN.smi
wget -P zinc_data/EH/AARN http://files.docking.org/3D/EH/AARN/EHAARN.smi
wget -P zinc_data/EH/ABRN http://files.docking.org/3D/EH/ABRN/EHABRN.smi
wget -P zinc_data/EI/AARN http://files.docking.org/3D/EI/AARN/EIAARN.smi
wget -P zinc_data/EI/ABRN http://files.docking.org/3D/EI/ABRN/EIABRN.smi
wget -P zinc_data/EJ/AARN http://files.docking.org/3D/EJ/AARN/EJAARN.smi
wget -P zinc_data/EJ/ABRN http://files.docking.org/3D/EJ/ABRN/EJABRN.smi
wget -P zinc_data/FG/AARN http://files.docking.org/3D/FG/AARN/FGAARN.smi
wget -P zinc_data/FG/ABRN http://files.docking.org/3D/FG/ABRN/FGABRN.smi
wget -P zinc_data/FH/AARN http://files.docking.org/3D/FH/AARN/FHAARN.smi
wget -P zinc_data/FH/ABRN http://files.docking.org/3D/FH/ABRN/FHABRN.smi
wget -P zinc_data/FI/AARN http://files.docking.org/3D/FI/AARN/FIAARN.smi
wget -P zinc_data/FI/ABRN http://files.docking.org/3D/FI/ABRN/FIABRN.smi
wget -P zinc_data/FJ/AARN http://files.docking.org/3D/FJ/AARN/FJAARN.smi
wget -P zinc_data/FJ/ABRN http://files.docking.org/3D/FJ/ABRN/FJABRN.smi
wget -P zinc_data/GF/AARN http://files.docking.org/3D/GF/AARN/GFAARN.smi
wget -P zinc_data/GF/ABRN http://files.docking.org/3D/GF/ABRN/GFABRN.smi
wget -P zinc_data/GG/AARN http://files.docking.org/3D/GG/AARN/GGAARN.smi
wget -P zinc_data/GG/ABRN http://files.docking.org/3D/GG/ABRN/GGABRN.smi
wget -P zinc_data/GH/AARN http://files.docking.org/3D/GH/AARN/GHAARN.smi
wget -P zinc_data/GH/ABRN http://files.docking.org/3D/GH/ABRN/GHABRN.smi
wget -P zinc_data/GI/AARN http://files.docking.org/3D/GI/AARN/GIAARN.smi
wget -P zinc_data/GI/ABRN http://files.docking.org/3D/GI/ABRN/GIABRN.smi
wget -P zinc_data/GJ/AARN http://files.docking.org/3D/GJ/AARN/GJAARN.smi
wget -P zinc_data/GJ/ABRN http://files.docking.org/3D/GJ/ABRN/GJABRN.smi
wget -P zinc_data/HF/AARN http://files.docking.org/3D/HF/AARN/HFAARN.smi
wget -P zinc_data/HF/ABRN http://files.docking.org/3D/HF/ABRN/HFABRN.smi
wget -P zinc_data/HG/AARN http://files.docking.org/3D/HG/AARN/HGAARN.smi
wget -P zinc_data/HG/ABRN http://files.docking.org/3D/HG/ABRN/HGABRN.smi
wget -P zinc_data/HH/AARN http://files.docking.org/3D/HH/AARN/HHAARN.smi
wget -P zinc_data/HH/ABRN http://files.docking.org/3D/HH/ABRN/HHABRN.smi
wget -P zinc_data/HI/AARN http://files.docking.org/3D/HI/AARN/HIAARN.smi
wget -P zinc_data/HI/ABRN http://files.docking.org/3D/HI/ABRN/HIABRN.smi
wget -P zinc_data/HJ/AARN http://files.docking.org/3D/HJ/AARN/HJAARN.smi
wget -P zinc_data/HJ/ABRN http://files.docking.org/3D/HJ/ABRN/HJABRN.smi
wget -P zinc_data/IF/AARN http://files.docking.org/3D/IF/AARN/IFAARN.smi
wget -P zinc_data/IF/ABRN http://files.docking.org/3D/IF/ABRN/IFABRN.smi
wget -P zinc_data/IG/AARN http://files.docking.org/3D/IG/AARN/IGAARN.smi
wget -P zinc_data/IG/ABRN http://files.docking.org/3D/IG/ABRN/IGABRN.smi
wget -P zinc_data/IH/AARN http://files.docking.org/3D/IH/AARN/IHAARN.smi
wget -P zinc_data/IH/ABRN http://files.docking.org/3D/IH/ABRN/IHABRN.smi
wget -P zinc_data/II/AARN http://files.docking.org/3D/II/AARN/IIAARN.smi
wget -P zinc_data/II/ABRN http://files.docking.org/3D/II/ABRN/IIABRN.smi
wget -P zinc_data/IJ/AARN http://files.docking.org/3D/IJ/AARN/IJAARN.smi
wget -P zinc_data/IJ/ABRN http://files.docking.org/3D/IJ/ABRN/IJABRN.smi
wget -P zinc_data/JF/AARN http://files.docking.org/3D/JF/AARN/JFAARN.smi
wget -P zinc_data/JF/ABRN http://files.docking.org/3D/JF/ABRN/JFABRN.smi
wget -P zinc_data/JG/AARN http://files.docking.org/3D/JG/AARN/JGAARN.smi
wget -P zinc_data/JG/ABRN http://files.docking.org/3D/JG/ABRN/JGABRN.smi
wget -P zinc_data/JH/AARN http://files.docking.org/3D/JH/AARN/JHAARN.smi
wget -P zinc_data/JH/ABRN http://files.docking.org/3D/JH/ABRN/JHABRN.smi
wget -P zinc_data/JI/AARN http://files.docking.org/3D/JI/AARN/JIAARN.smi
wget -P zinc_data/JI/ABRN http://files.docking.org/3D/JI/ABRN/JIABRN.smi
wget -P zinc_data/JJ/AARN http://files.docking.org/3D/JJ/AARN/JJAARN.smi
wget -P zinc_data/JJ/ABRN http://files.docking.org/3D/JJ/ABRN/JJABRN.smi
echo 'Download complete!'
